CREATE TABLE EVENTO (
	EVENTO_ID INTEGER NOT NULL IDENTITY,
	NOME VARCHAR(255) NOT NULL,
	[DATA] DATETIME NOT NULL,
	PRIMARY KEY (EVENTO_ID)
)
GO

CREATE TABLE CONVIDADO (
	CONVIDADO_ID INTEGER NOT NULL IDENTITY,
	EVENTO_ID INTEGER NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	[STATUS] INTEGER NOT NULL,
	PRIMARY KEY (CONVIDADO_ID),
	FOREIGN KEY (EVENTO_ID) REFERENCES EVENTO(EVENTO_ID)
)
GO
